"""empty message

Revision ID: ecf6c3456a3a
Revises: f7edc69ea1bb
Create Date: 2019-09-05 23:39:35.553389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf6c3456a3a'
down_revision = 'f7edc69ea1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('agenda_slug', table_name='person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('agenda_slug', 'person', ['agenda_slug'], unique=True)
    # ### end Alembic commands ###
