"""empty message

Revision ID: f7edc69ea1bb
Revises: a7805cd618d5
Create Date: 2019-09-04 00:40:31.806529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7edc69ea1bb'
down_revision = 'a7805cd618d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('agenda_slug', sa.String(length=120), nullable=False))
    op.add_column('person', sa.Column('phone', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'person', ['agenda_slug'])
    op.create_unique_constraint(None, 'person', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'phone')
    op.drop_column('person', 'agenda_slug')
    # ### end Alembic commands ###
